config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    delete "cart_items/destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post "orders/confirm", as: "confirm_orders"
    get "orders/thanks", as: "thanks_orders"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get "customers/my_page" => "customers#show", as: "my_page_customers"
    get "customers/information/edit" => "customers#edit", as: "edit_information_customers"
    patch "customers/information" => "customers#update", as: "information_customers"
    get "customers/unsubscribe", as: "unsubscribe_customers"
    patch "customers/withdraw", as: "withdraw_customers"
  end


  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses
  has_many :cart_items
  has_many :orders
  
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details
  belongs_to :genre

  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def get_image(width,height)
    image.variant(resize_to_limit: [width,height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {credit_card: 0, transfer: 1 }
  enum order_status: {awaiting_payment: 0, payment_confirmation: 1,
    under_manufacture: 2, preparing_to_ship: 3, already_shipped: 4 }

  belongs_to :customer
  has_many :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum production_status: { not_initiated: 0, awaiting_manufacture: 1,
    under_manufacture: 2, manufacturing_completed: 3 }

  belongs_to :order
  belongs_to :item

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  before_action :authenticate_admin!
  
  def top
    @orders = Order.page(params[:page])
    @total_amount = OrderDetail.all.sum(:amount)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :in_active, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    if order.order_status == "payment_confirmation"
      order_details = OrderDetail.where(order_id: order.id)
      order_details.each do |order_detail|
        order_detail.update(production_status: 1)
      end
    end
    redirect_to admin_order_path(order.id)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<%= render "admin/shared/header" %>

<body>
  <div class="container" style="height: 650px">
    <div class="row">
      <div class="col-4 text-center pt-4">
        <p class="h4 bg-light">ジャンル編集</p>
      </div>
    </div>

    <div class="row">
      <div class="col pt-5">
        <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
          <%= f.label :name, "ジャンル名" %>
          <%= f.text_field :name, class: "ml-5" %>
          <%= f.submit "変更を保存", class: "btn btn-success ml-5" %>
        <% end %>
      </div>
    </div>
  </div>
</body>

<footer class="border"></footer>

app/views/admin/genres/index.html.erb
<%= render "admin/shared/header" %>

<body>
  <div class="container-fluid" style="height: 650px">
    <div class="row">
      <div class="col-4 offset-1 text-center pt-3">
        <p class="h4 bg-light">ジャンル一覧・追加</p>
      </div>
    </div>

    <div class="row pt-3">
      <div class="col offset-1 mt-4">
        <%= form_with model: @genre, url: "/admin/genres", method: :post do |f| %>
          <%= f.label :name, "ジャンル名" %>
          <%= f.text_field :name, :placeholder => "ジャンル名" , class: "ml-5" %>
          <%= f.submit "　新規登録　", class: "btn btn-success ml-5" %>
        <% end %>
      </div>
    </div>

    <div class="row mt-5">
      <div class="col-4 offset-1">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th class="text-center">ジャンル</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
            <tr>
              <td>
                <%= genre.name %>
              </td>
              <td class="text-center">
                <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-sm btn-success" %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</body>

<footer class="border"></footer>

app/views/admin/items/edit.html.erb
<%= render "admin/shared/header" %>


<body>
  <div class="container" style="height: 650px">

    <div class="row">
      <div class="col-3 offset-1 text-center pt-3">
        <p class="h4 bg-light">商品編集</p>
      </div>
    </div>

    <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
      <div class="form-group row pt-4">
        <%= f.label :image, "商品画像", class: "col-md-2 col-form-label" %>
        <div class="col-md-8">
          <%= f.file_field :image, accept: "image/*", class: "form-control-file" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :name, "商品名", class: "col-md-2 col-form-label" %>
        <div class="col-md-8">
         <%= f.text_field :name, :placeholder => "商品名", class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :introduction, "商品説明", class: "col-md-2 col-form-label" %>
        <div class="col-md-8">
          <%= f.text_area :introduction, :placeholder => "ここに説明文を記述します", class: "form-control", rows: "5" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :genre_id, "ジャンル", class: "col-md-2 col-form-label" %>
        <div class="col-md-8">
          <%= f.collection_select(:genre_id, @genres, :id, :name, {prompt: "-- 選択してください --"}, {class: "form-control"}) %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :price, "税抜価格", class: "col-md-2 col-form-label" %>
        <div class="col-md-8">
          <%= f.text_field :price, :placeholder => "1000", class: "form-control" %>
        </div>
        <%= f.label :price, "円" %>
      </div>

      <div class="form-group row">
        <%= f.label :in_active, "販売ステータス", class: "col-md-2 col-form-label" %>
        <div class="col-md-8">
          <%= f.radio_button :in_active, :true %>
          <%= f.label :in_active, "販売中" %>
          <%= f.radio_button :in_active, :false %>
          <%= f.label :in_active, "販売停止中" %>
        </div>
      </div>

      <div class="form_group row pb-4">
        <div class="col text-center">
          <%= f.submit "　変更を保存　", class: "btn btn-success btn-lg" %>
        </div>
      </div>
    <% end %>

  </div>

</body>

<footer class="border"></footer>

app/views/admin/items/index.html.erb
<%= render "admin/shared/header" %>

<body>
  <div class="container-fluid" style="height: 650px">
    <div class="row pt-3">
      <div class="col-3 offset-1 text-center">
        <p class="h4 bg-light">商品一覧</p>
      </div>
      <div class="col-2 offset-6">
        <%= link_to new_admin_item_path, class: "text-dark" do %>
          <i class="fas fa-plus fa-2x"></i>
        <% end %>
      </div>
    </div>

    <div class="row pt-3">
      <div class="col-10 offset-1">
        <table class="table table-sm table-borderless border-bottom">
          <thead>
            <tr class="table-secondary">
              <th style="width: 10%">商品ID</th>
              <th style="width: 30%">商品名</th>
              <th style="width: 10%">税抜価格</th>
              <th style="width: 30%">ジャンル</th>
              <th style="width: 20%">ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td>
                <ins>
                  <%= link_to admin_item_path(item.id), class: "text-dark" do %>
                    <%= item.name %>
                  <% end %>
                </ins>
              </td>
              <td><%= item.price.to_s(:delimited) %></td>
              <td><%= item.genre.name %></td>
              <td>
                <% if item.in_active? %>
                  <p class="text-success"><strong>販売中</strong></p>
                <% else %>
                  <p class="text-secondary"><strong>販売停止中</strong></p>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= paginate @items %>
      </div>
    </div>

  </div>
</body>

  <footer class="border"></footer>

app/views/admin/items/new.html.erb
<%= render "admin/shared/header" %>


<body>
  <div class="container" style="height: 650px">
    <div class="row">
      <div class="col-4 text-center pt-3">
        <span class="h4 bg-light">　商品新規登録　</span>
      </div>
    </div>

    <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
      <div class="form-group row mt-5">
        <%= f.label :image, "商品画像", class: "col-md-2 col-form-label" %>
        <div class="col-md-8">
          <%= f.file_field :image, accept: "image/*", class: "form-control-file" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :name, "商品名", class: "col-md-2 col-form-label" %>
        <div class="col-md-8">
          <%= f.text_field :name, :placeholder => "商品名", class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :introduction, "商品説明", class: "col-md-2 col-form-label" %>
        <div class="col-md-8">
          <%= f.text_area :introduction, :placeholder => "ここに説明文を記述します", class: "form-control", rows: "5" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :genre_id, "ジャンル", class: "col-md-2 col-form-label" %>
        <div class="col-md-8">
          <%= f.collection_select(:genre_id, @genres, :id, :name, {prompt: "-- 選択してください --"}, {class: "form-control"}) %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :price, "税抜価格", class: "col-md-2 col-form-label" %>
        <div class="col-md-8">
          <%= f.text_field :price, :placeholder => "1000", class: "form-control" %>
        </div>
        <%= f.label :price, "円" %>
      </div>
      <div class="form-group row">
        <%= f.label :in_active, "販売ステータス", class: "col-md-2 col-form-label" %>
        <div class="col-md-8">
          <%= f.radio_button :in_active, :true %>
          <%= f.label :in_active, "販売中" %>
          <%= f.radio_button :in_active, :false %>
          <%= f.label :in_active, "販売停止中" %>
        </div>
      </div>
      <div class="form_group row pb-4">
        <div class="col text-center">
          <%= f.submit "　新規登録　", class: "btn btn-success btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</body>

<footer class="border"></footer>

app/views/admin/items/show.html.erb
<%= render "admin/shared/header" %>



<body>
  <div class="container-fluid" style="height: 650px">
    <div class="row">
      <div class="col-3 offset-1 text-center pt-3">
        <p class="h4 bg-light">商品詳細</p>
      </div>
    </div>

    <div class="row mt-5">
      <div class="col-3 offset-1">
        <%= image_tag @item.get_image(200,300) %>
      </div>

      <div class="col-6">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td  style="width: 35%">商品名</td>
              <td class="h5"><%= @item.name %></td>
            </tr>
            <tr>
              <td style="width: 35%">商品説明</td>
              <td class="h5"><%= @item.introduction %></td>
            </tr>
            <tr>
              <td style="width: 35%">ジャンル</td>
              <td class="h5"><%= @item.genre.name %></td>
            </tr>
            <tr>
              <td style="width: 35%">税込価格</br>(税抜価格)</td>
              <td class="h5"><%= (@item.price*1.1).round.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>)円</td>
            </tr>
            <tr>
              <td style="width: 35%">販売ステータス</td>
              <td class="h5">
                <% if @item.in_active? %>
                  <p class="text-success"><strong>販売中</strong></p>
                <% else %>
                  <p class="text-secondary"><strong>販売停止中</strong></p>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row justify-content-center">
      <%= link_to "　編集する　", edit_admin_item_path(@item.id), class: "col-2 btn btn-success btn-lg" %>
    </div>

  </div>
</body>

<footer class="border"></footer>

app/views/admin/orders/show.html.erb
<%= render "admin/shared/header" %>


<body>

  <div class="container" style="height: 650px">
    <div class="row">
      <div class="col-4 text-center pt-3">
        <p class="h4 bg-light">注文履歴詳細</p>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <table class="table table-borderless table-sm">
          <tbody>
            <tr>
              <th>購入者</th>
              <td>
                <ins>
                <%= link_to admin_customer_path(@order.customer.id), class: "text-body" do %>
                <%= @order.customer.last_name %><%= @order.customer.first_name %>
                <% end %>
                </ins>
              </td>
            </tr>
            <tr>
              <th>注文日</th>
              <td><%= @order.created_at.strftime('%Y/%m/%d')%></td>
            </tr>
            <tr>
              <th>配送先</th>
              <td>
                〒<%= @order.postal_code %><%= @order.address %></br>
                <%= @order.name %>
              </td>
            </tr>
            <tr>
              <th>支払い方法</th>
              <td><%= @order.payment_method_i18n %></td>
            </tr>
            <tr>
              <th>注文ステータス</th>
              <td>
                <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
                  <%= f.select :order_status, Order.order_statuses_i18n.invert, {}, {class: "form-control-sm"} %>
                  <%= f.submit "更新", class: "btn btn-success btn-sm" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 col-lg-9">
        <table class="table">
          <thead>
            <tr class="table-secondary">
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th>製作ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @order_details.each do |order_detail| %>
            <tr>
              <td>
                <%= order_detail.item.name %>
              </td>
              <td>
                <%= order_detail.price_at_purchase.to_s(:delimited) %>
              </td>
              <td>
                <%= order_detail.amount %>
              </td>
              <td>
                <%= (order_detail.price_at_purchase*order_detail.amount).to_s(:delimited) %>
              </td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
                  <%= f.select :production_status, OrderDetail.production_statuses_i18n.invert, {}, {class: "form-control-sm"} %>
                  <%= f.submit "更新", class: "btn btn-success btn-sm" %>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="col-md-4 col-lg-3 align-self-end">
        <table class="table table-sm table-borderless">
          <tr>
            <th>商品合計</th>
            <td><%= (@order.total_price-@order.postage).to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td><%= @order.postage %>円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td><%= @order.total_price.to_s(:delimited) %>円</td>
          </tr>

        </table>
      </div>
    </div>
  </div>

</body>

<footer class="border"></footer>