config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    delete "cart_items/destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post "orders/confirm", as: "confirm_orders"
    get "orders/thanks", as: "thanks_orders"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get "customers/my_page" => "customers#show", as: "my_page_customers"
    get "customers/information/edit" => "customers#edit", as: "edit_information_customers"
    patch "customers/information" => "customers#update", as: "information_customers"
    get "customers/unsubscribe", as: "unsubscribe_customers"
    patch "customers/withdraw", as: "withdraw_customers"
  end


  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses
  has_many :cart_items
  has_many :orders
  
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details
  belongs_to :genre

  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def get_image(width,height)
    image.variant(resize_to_limit: [width,height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {credit_card: 0, transfer: 1 }
  enum order_status: {awaiting_payment: 0, payment_confirmation: 1,
    under_manufacture: 2, preparing_to_ship: 3, already_shipped: 4 }

  belongs_to :customer
  has_many :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum production_status: { not_initiated: 0, awaiting_manufacture: 1,
    under_manufacture: 2, manufacturing_completed: 3 }

  belongs_to :order
  belongs_to :item

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  before_action :authenticate_admin!
  
  def top
    @orders = Order.page(params[:page])
    @total_amount = OrderDetail.all.sum(:amount)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :in_active, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_header.html.erb
<header class="border">

  <nav class="navbar navbar-expand-sm navbar-light">

    <%= link_to "　LOGO　", root_path ,class: "h1 text-decoration-none text-dark border border-secondary" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse d-flex flex-column" id="navbar">
      <ul class="navbar-nav ml-auto mt-3">
        <% if admin_signed_in? %>
        <li class="nav-item">
            <%= link_to "商品一覧" , admin_items_path ,class: "nav-link btn btn-sm btn-outline-dark mr-4" %>
          </li>
          <li class="nav-item">
            <%= link_to "会員一覧" , admin_customers_path ,class: "nav-link btn btn-sm btn-outline-dark mr-4" %>
          </li>
          <li class="nav-item">
            <%= link_to "注文履歴一覧" , admin_root_path ,class: "nav-link btn btn-sm btn-outline-dark mr-4" %>
          </li>
          <li class="nav-item">
            <%= link_to "ジャンル一覧" , admin_genres_path ,class: "nav-link btn btn-sm btn-outline-dark mr-4" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト" , destroy_admin_session_path , method: :delete ,class: "nav-link btn btn-sm btn-outline-dark" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "About" , about_path ,class: "nav-link btn btn-sm btn-outline-dark mr-4" %>
          </li>
          <li class="nav-item">
            <%= link_to "商品一覧" , items_path ,class: "nav-link btn btn-sm btn-outline-dark mr-4" %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録" , new_customer_registration_path ,class: "nav-link btn btn-sm btn-outline-dark mr-4" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン" , new_customer_session_path ,class: "nav-link btn btn-sm btn-outline-dark" %>
          </li>
        <% end %>
      </ul>

      <div class="input-group justify-content-end mt-3 mb-2">
        <input class="input-group-prepend" placeholder="Search"></input>
        <span class="input-group-btn input-group-append">
          <submit class="btn btn-outline-dark btn-sm"><i class="fas fa-search"></i></submit>
        </span>
      </div>

    </div>
  </nav>

</header>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>